### ISSUE TITLE
Silent failure issue / Action does not fail if an exception is thrown

### ISSUE THREAD

**Issue by filfreire** [SSLcom/actions-codesigner#5]
We've noticed the action will not throw a failure state if an `java.io.IOException` is thrown when running the codesign.

So for example, something like the following log:
```
Run CodeSigner
  Running ESigner.com CodeSign Action ====>
  
  java.io.IOException: Source '/github/workspace/artifacts/windows-latest-artifacts/insomnia/dist/squirrel-windows/Insomnia.Core-2022.7.0-alpha.0.exe' and destination '/github/workspace/artifacts/windows-latest-artifacts/insomnia/dist/squirrel-windows/Insomnia.Core-2022.7.0-alpha.0.exe' are the same
  	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:874)
  	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:835)
  	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:802)
  	at com.ssl.code.signing.tool.commands.SignCommand.run(SignCommand.java:250)
  	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
  	at picocli.CommandLine.access$1300(CommandLine.java:145)
  	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
  	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
  	at picocli.CommandLine.execute(CommandLine.java:2078)
  	at com.ssl.code.signing.tool.CodeSignTool.main(CodeSignTool.java:35)
```

Is still picked up as being a successful run on Github, even though the code signing didn't happen. Example of this happening can be found [here](https://github.com/Kong/insomnia/actions/runs/3677488325/jobs/6219514213#step:6:20)

![image](https://user-images.githubusercontent.com/11976836/207137884-8f75f410-2f8d-4bfb-b0ef-58e08204a0f5.png)

Possible workaround fix could be changing [this check](https://github.com/SSLcom/actions-codesigner/blob/0d06aa6de4cdc96f9a182e8dad145e3a791d72fa/entrypoint.sh#L22) to also parse for `Exception`.

cc @ruby-dev

**Comment by bayrakmustafa** [comment]
@filfreire we have made an improvement for this issue. Can you try again with the develop version?

/cc @ruby-dev

**Comment by bayrakmustafa** [comment]
@filfreire You can use https://github.com/SSLcom/esigner-codesign project. https://github.com/SSLcom/actions-codesigner is deprecated.
